package org.apache.jsp.Admin.sub;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.commons.dbutils.*;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang.math.NumberUtils;

public final class left_005fmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=euc-kr\">\n");
      out.write("<link href=\"../style.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#menu2 {\n");
      out.write("\tdisplay:none\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script language=\"JavaScript\">\n");
      out.write("\t\t<!--\n");
      out.write("\t\t\tfunction toggleMenu(currMenu) {\n");
      out.write("\t\t\t\tif (document.all) {\n");
      out.write("\t\t\t\t\tthisMenu = eval(\"document.all.menu2[\" + (currMenu-1) + \"].style\");\n");
      out.write("\t\t\t\t\tif (thisMenu.display == \"block\") {\n");
      out.write("\t\t\t\t\t\tthisMenu.display = \"none\";\n");
      out.write("\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\tfor(i=0;i<document.all.menu2.length;i++) {\n");
      out.write("\t\t\t\t\t\t\totherMenu = eval(\"document.all.menu2[\" + i + \"].style\");\n");
      out.write("\t\t\t\t\t\t\totherMenu.display = \"none\";\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\tthisMenu.display = \"block\";\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\treturn true;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t//-->\n");
      out.write("\t\t</script>\n");
      out.write("</head>\n");
      out.write("<body bgcolor=\"#666666\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\" background=\"../images/common/admin_bg.jpg\">\n");
      out.write("<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"180\">\n");
      out.write("  <tr>\n");
      out.write("    <td width=\"145\" align=\"center\"><img src=\"../images/common/goodjobgolf_logo.gif\" width=\"180\" height=\"80\" border=\"0\"></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td width=\"145\" align=\"center\">&nbsp;</td>\n");
      out.write("  </tr>\n");
      out.write("</table>\n");
      out.write("<table width=\"180\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\">\n");
      out.write("    <tr>\n");
      out.write("        <td width=\"180\" valign=\"top\">\n");
      out.write("            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("                <tr>\n");
      out.write("                    <td>\n");
      out.write("                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                            <tr>\n");
      out.write("                                <td width=\"20\" height=\"25\" align=\"center\"><img src=\"../images/common/menu_bullet.gif\" width=\"4\" height=\"4\" align=\"absmiddle\"></td>\n");
      out.write("                                <td width=\"160\" ONCLICK=\"return toggleMenu(1)\" STYLE=\"cursor:hand\"><b><font color=\"white\">메인관리</font></b></td>\n");
      out.write("                            </tr>\n");
      out.write("                        </table>\n");
      out.write("                        <table id=\"menu2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("                            <tr>\n");
      out.write("                                <td width=\"20\" height=\"22\">&nbsp;</td>\n");
      out.write("                                <td width=\"160\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"#\" class=left_menu>상품등록</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                        </table>\n");
      out.write("                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                            <tr>\n");
      out.write("                                <td width=\"20\" height=\"25\" align=\"center\"><img src=\"../images/common/menu_bullet.gif\" width=\"4\" height=\"4\" align=\"absmiddle\"></td>\n");
      out.write("                                <td width=\"160\" ONCLICK=\"return toggleMenu(2)\" STYLE=\"cursor:hand\"><b><font color=\"white\">상품관리</font></b></td>\n");
      out.write("                            </tr>\n");
      out.write("                        </table>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>\n");
      out.write("                        <table id=\"menu2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("                            <tr>\n");
      out.write("                                <td height=\"22\">&nbsp;</td>\n");
      out.write("                                <td width=\"160\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"golfclub/golfclub_realtime_list.html\" class=left_menu>실시간예약</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td height=\"22\">&nbsp;</td>\n");
      out.write("                                <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"golfclub/golfclub_before_list.html\" class=left_menu>사전예약</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td height=\"22\">&nbsp;</td>\n");
      out.write("                                <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"package/domestic_list.html\" class=left_menu>국내패키지</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td height=\"22\">&nbsp;</td>\n");
      out.write("                                <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"package/overseas_list.html\" class=left_menu>해외패키지</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td height=\"22\">&nbsp;</td>\n");
      out.write("                                <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"condo/condo_list.html\" class=left_menu>콘도</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td height=\"22\">&nbsp;</td>\n");
      out.write("                                <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"#\" class=left_menu>소셜커머스</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                        </table>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                <tr>\n");
      out.write("                    <td width=\"20\" height=\"25\" align=\"center\"><img src=\"../images/common/menu_bullet.gif\" width=\"4\" height=\"4\" align=\"absmiddle\"></td>\n");
      out.write("                    <td width=\"160\" ONCLICK=\"return toggleMenu(3)\" STYLE=\"cursor:hand\"><b><font color=\"white\">예약관리</font></b></td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("            <table id=\"menu2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("                <tr>\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\n");
      out.write("                    <td width=\"160\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"booking/realtime_list.html\" class=left_menu>실시간예약</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\n");
      out.write("                    <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"booking/before_list.html\" class=left_menu>사전예약</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\n");
      out.write("                    <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"booking/domestic_list.html\"\" class=left_menu>국내패키지</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\n");
      out.write("                    <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"booking/overseas_list.html\"\" class=left_menu>해외패키지</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\n");
      out.write("                    <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"booking/condo_list.html\" class=left_menu>콘도</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\n");
      out.write("                    <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"#\" class=left_menu>소셜커머스</a></td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                <tr>\n");
      out.write("                    <td width=\"20\" height=\"25\" align=\"center\"><img src=\"../images/common/menu_bullet.gif\" width=\"4\" height=\"4\" align=\"absmiddle\"></td>\n");
      out.write("                    <td width=\"160\" ONCLICK=\"return toggleMenu(4)\" STYLE=\"cursor:hand\"><b><font color=\"white\">회원관리</font></b></td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("            <table id=\"menu2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("                <tr>\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\n");
      out.write("                    <td width=\"160\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"member/mem_list.jsp\" class=left_menu>회원가입현황</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\n");
      out.write("                    <td width=\"160\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"#\" class=left_menu>SMS 보내기</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\n");
      out.write("                    <td width=\"160\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"#\" class=left_menu>E-Mail 보내기</a></td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("                <tr>\n");
      out.write("                    <td>\n");
      out.write("                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                            <tr>\n");
      out.write("                                <td width=\"20\" height=\"25\" align=\"center\"><img src=\"../images/common/menu_bullet.gif\" width=\"4\" height=\"4\" align=\"absmiddle\"></td>\n");
      out.write("                                <td width=\"160\" ONCLICK=\"toggleMenu(5)\" STYLE=\"cursor:hand\"><font color=\"white\"><b>통계관리</b></font></td>\n");
      out.write("                            </tr>\n");
      out.write("                        </table>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>\n");
      out.write("                        <table id=\"menu2\" name=\"menu2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("                            <tr>\n");
      out.write("                                <td width=\"20\" height=\"25\">&nbsp;</td>\n");
      out.write("                                <td width=\"160\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"#\" class=left_menu>신규회원분석</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td height=\"25\">&nbsp;</td>\n");
      out.write("                                <td><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a href=\"#\" target=\"main\" class=left_menu>방문자분석</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td height=\"25\">&nbsp;</td>\n");
      out.write("                                <td><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a href=\"#\" target=\"main\" class=left_menu>결제수단분석</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td height=\"25\">&nbsp;</td>\n");
      out.write("                                <td><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a href=\"#\" target=\"main\" class=left_menu>인기골프장분석</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                        </table>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("                <tr>\n");
      out.write("                    <td>\n");
      out.write("                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                            <tr>\n");
      out.write("                                <td width=\"20\" height=\"25\" align=\"center\"><img src=\"../images/common/menu_bullet.gif\" width=\"4\" height=\"4\" align=\"absmiddle\"></td>\n");
      out.write("                                <td width=\"160\" ONCLICK=\"toggleMenu(6)\" STYLE=\"cursor:hand\"><font color=\"white\"><b>게시판관리</b></font></td>\n");
      out.write("                            </tr>\n");
      out.write("                        </table>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>\n");
      out.write("                        <table id=\"menu2\" name=\"menu2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("                            <tr>\n");
      out.write("                                <td height=\"25\" width=\"20\">&nbsp;</td>\n");
      out.write("                                <td width=\"160\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"board/notice_list.html\" class=left_menu>공지사항</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td height=\"25\" width=\"20\">&nbsp;</td>\n");
      out.write("                                <td width=\"160\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"board/faq_list.html\" class=left_menu>FAQ</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td height=\"25\" width=\"20\">&nbsp;</td>\n");
      out.write("                                <td width=\"160\"><img align=\"absmiddle\" src=\"../images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"board/join_list.html\" class=left_menu>JOIN 커뮤니티</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                        </table>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("        </td>\n");
      out.write("    </tr>\n");
      out.write("</table>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
