package org.apache.jsp._005fadmin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class left_005fmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=euc-kr\">\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<style type=\"text/css\"> \r\n");
      out.write("#menu2 {\r\n");
      out.write("\tdisplay:none\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("\t\t<!--\r\n");
      out.write("\t\t\tfunction toggleMenu(currMenu) {\r\n");
      out.write("\t\t\t\tif (document.all) {\r\n");
      out.write("\t\t\t\t\tthisMenu = eval(\"document.all.menu2[\" + (currMenu-1) + \"].style\");\r\n");
      out.write("\t\t\t\t\tif (thisMenu.display == \"block\") {\r\n");
      out.write("\t\t\t\t\t\tthisMenu.display = \"none\";\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tfor(i=0;i<document.all.menu2.length;i++) {\r\n");
      out.write("\t\t\t\t\t\t\totherMenu = eval(\"document.all.menu2[\" + i + \"].style\");\r\n");
      out.write("\t\t\t\t\t\t\totherMenu.display = \"none\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tthisMenu.display = \"block\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t//-->\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#666666\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\" background=\"/_admin/images/common/admin_bg.jpg\">\r\n");
      out.write("<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"180\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"145\" align=\"center\"><img src=\"/_admin/images/common/goodjobgolf_logo.gif\" width=\"180\" height=\"80\" border=\"0\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"145\" align=\"center\">&nbsp;</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table width=\"180\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"180\" valign=\"top\">\r\n");
      out.write("            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <!--table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td width=\"20\" height=\"25\" align=\"center\"><img src=\"/_admin/images/common/menu_bullet.gif\" width=\"4\" height=\"4\" align=\"absmiddle\"></td>\r\n");
      out.write("                                <td width=\"160\" ONCLICK=\"return toggleMenu(1)\" STYLE=\"cursor:hand\"><b><font color=\"white\">메인관리</font></b></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table-->\r\n");
      out.write("                        <table id=\"menu2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td width=\"20\" height=\"22\">&nbsp;</td>\r\n");
      out.write("                                <td width=\"160\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"#\" class=left_menu>상품등록</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td width=\"20\" height=\"25\" align=\"center\"><img src=\"/_admin/images/common/menu_bullet.gif\" width=\"4\" height=\"4\" align=\"absmiddle\"></td>\r\n");
      out.write("                                <td width=\"160\" ONCLICK=\"return toggleMenu(2)\" STYLE=\"cursor:hand\"><b><font color=\"white\">상품관리</font></b></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <table id=\"menu2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td height=\"22\">&nbsp;</td>\r\n");
      out.write("                                <td width=\"160\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"product/real_list.jsp?menu=1\" class=left_menu>실시간예약</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td height=\"22\">&nbsp;</td>\r\n");
      out.write("                                <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"product/pre_list.jsp?menu=2\" class=left_menu>사전예약</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td height=\"22\">&nbsp;</td>\r\n");
      out.write("                                <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"product/package_list.jsp?menu=3\" class=left_menu>국내패키지</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td height=\"22\">&nbsp;</td>\r\n");
      out.write("                                <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"package/overseas_list.html\" class=left_menu>해외패키지</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td height=\"22\">&nbsp;</td>\r\n");
      out.write("                                <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"product/condo_list.jsp?menu=4\" class=left_menu>콘도</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td height=\"22\">&nbsp;</td>\r\n");
      out.write("                                <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"#\" class=left_menu>소셜커머스</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td width=\"20\" height=\"25\" align=\"center\"><img src=\"/_admin/images/common/menu_bullet.gif\" width=\"4\" height=\"4\" align=\"absmiddle\"></td>\r\n");
      out.write("                    <td width=\"160\" ONCLICK=\"return toggleMenu(3)\" STYLE=\"cursor:hand\"><b><font color=\"white\">예약관리</font></b></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <table id=\"menu2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"160\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"order/real_list.jsp\" class=left_menu>실시간예약</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"order/pre_list.jsp\" class=left_menu>사전예약</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"order/package_list.jsp\"\" class=left_menu>국내패키지</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"booking/overseas_list.html\"\" class=left_menu>해외패키지</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"order/condo_list.jsp\" class=left_menu>콘도</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"160\" height=\"22\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"#\" class=left_menu>소셜커머스</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td width=\"20\" height=\"25\" align=\"center\"><img src=\"/_admin/images/common/menu_bullet.gif\" width=\"4\" height=\"4\" align=\"absmiddle\"></td>\r\n");
      out.write("                    <td width=\"160\" ONCLICK=\"return toggleMenu(4)\" STYLE=\"cursor:hand\"><b><font color=\"white\">회원관리</font></b></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <table id=\"menu2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"160\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"/_admin/member/mem_list.jsp\" class=left_menu>회원가입현황</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"160\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"/_admin/member/sms_list.jsp\" class=left_menu>SMS 보내기</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"22\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"160\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"/_admin/member/mail_list.jsp\" class=left_menu>E-Mail 보내기</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td width=\"20\" height=\"25\" align=\"center\"><img src=\"/_admin/images/common/menu_bullet.gif\" width=\"4\" height=\"4\" align=\"absmiddle\"></td>\r\n");
      out.write("                                <td width=\"160\" ONCLICK=\"toggleMenu(5)\" STYLE=\"cursor:hand\"><font color=\"white\"><b>통계관리</b></font></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <table id=\"menu2\" name=\"menu2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td width=\"20\" height=\"25\">&nbsp;</td>\r\n");
      out.write("                                <td width=\"160\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"#\" class=left_menu>신규회원분석</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td height=\"25\">&nbsp;</td>\r\n");
      out.write("                                <td><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a href=\"#\" target=\"main\" class=left_menu>방문자분석</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td height=\"25\">&nbsp;</td>\r\n");
      out.write("                                <td><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a href=\"#\" target=\"main\" class=left_menu>결제수단분석</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td height=\"25\">&nbsp;</td>\r\n");
      out.write("                                <td><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a href=\"#\" target=\"main\" class=left_menu>인기골프장분석</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td width=\"20\" height=\"25\" align=\"center\"><img src=\"/_admin/images/common/menu_bullet.gif\" width=\"4\" height=\"4\" align=\"absmiddle\"></td>\r\n");
      out.write("                                <td width=\"160\" ONCLICK=\"toggleMenu(6)\" STYLE=\"cursor:hand\"><font color=\"white\"><b>게시판관리</b></font></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <table id=\"menu2\" name=\"menu2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td height=\"25\" width=\"20\">&nbsp;</td>\r\n");
      out.write("                                <td width=\"160\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"/_admin/board/notice_list.jsp\" class=left_menu>공지사항</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td height=\"25\" width=\"20\">&nbsp;</td>\r\n");
      out.write("                                <td width=\"160\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"/_admin/board/faq_list.jsp\" class=left_menu>FAQ</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td height=\"25\" width=\"20\">&nbsp;</td>\r\n");
      out.write("                                <td width=\"160\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"/_admin/board/join_list.jsp\" class=left_menu>JOIN 커뮤니티</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td height=\"25\" width=\"20\">&nbsp;</td>\r\n");
      out.write("                                <td width=\"160\"><img align=\"absmiddle\" src=\"/_admin/images/common/left_menu_bullet.gif\" width=\"6\" height=\"7\" border=\"0\"> <a target=\"main\" href=\"/_admin/board/partnership_list.jsp\" class=left_menu>제휴 및 관고문의</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
